version: '3.7'

networks:
  database_net:
    name: database_net
    driver: bridge

volumes:
  postgres-data:
services:
  bitbucket-extractor:
    image: msoa/bitbucket-extractor:latest
    ports:
      - 8080:8080
    depends_on:
      -  postgres
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      JAVA_OPS: "-Xms100m -Xmx1536m"
    networks:
      - database_net
  postgres:
    image: postgres
    container_name: postgres
    ports:
      - 25432:5432
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    networks:
      - database_net
